### ISSUE TITLE
Does this replace nvm?

### ISSUE THREAD

**Issue by nickbreaton** [aredridel/node-bin-gen#46]
Hello @aredridel. Thanks so much for publishing this awesome package. This is more of a question, but I think it may be useful to open an issue in case others also have it.

If using nvm on a project to keep a consistent version across developers, would this package completely replace this use case? I believe this to be the case, but a friend suggested that in some cases the global node version would be used, like on an initial `npm install`. Could you please clarify this for me and potentially others.

Thanks again.

**Comment by aredridel** [comment]
Yeah. It replaces `nvm` for me.

`npm install` does run with your system node, indeed, so a `npm rebuild` after that is smart. I'd love to solve that, but it's never actually bitten me.

It wouldn't take much in the way of wrappers to fix this up so that one can do the `node` install first, then runs that to run `npm install`. 

but TL;DR: yes, it can and does for me.

**Comment by nickbreaton** [comment]
Thank you. This was very helpful.

**Comment by fritx** [comment]
There are people using nvm, is this library gonna to support and reuse node versions installed by nvm?

For example, `/Users/{username}/.nvm/versions/node/v10.7.0/bin/node` in Mac

**Comment by aredridel** [comment]
It is not. Though that's not a bad feature to add to the shim module!
